/* Searchable concept / math-topic index used by global search.
 * Each entry: term, kind (mathematics/concept/statistics/application), url, models that use it.
 */
export const CONCEPTS = [
  { term: 'Gradient Descent', kind: 'mathematics', url: 'pages/mathematics.html#gradient-descent', models: ['Linear Regression', 'Logistic Regression', 'SVM'] },
  { term: 'Derivative', kind: 'mathematics', url: 'pages/mathematics.html#derivatives', models: ['Linear Regression', 'Logistic Regression'] },
  { term: 'Partial Derivative', kind: 'mathematics', url: 'pages/mathematics.html#partial-derivatives', models: ['Linear Regression', 'Multiple Linear Regression', 'Logistic Regression'] },
  { term: 'Loss Function', kind: 'mathematics', url: 'pages/mathematics.html#loss-function', models: ['All supervised models'] },
  { term: 'Cost Function', kind: 'mathematics', url: 'pages/mathematics.html#cost-function', models: ['Linear Regression', 'K-Means'] },
  { term: 'Entropy', kind: 'mathematics', url: 'pages/mathematics.html#entropy', models: ['Decision Tree'] },
  { term: 'Information Gain', kind: 'mathematics', url: 'pages/mathematics.html#information-gain', models: ['Decision Tree'] },
  { term: 'Gini Impurity', kind: 'mathematics', url: 'pages/decision-tree.html', models: ['Decision Tree'] },
  { term: 'Bayes Theorem', kind: 'mathematics', url: 'pages/mathematics.html#bayes-theorem', models: ['Naive Bayes'] },
  { term: 'Conditional Probability', kind: 'mathematics', url: 'pages/mathematics.html#conditional-probability', models: ['Naive Bayes'] },
  { term: 'Eigenvalue', kind: 'mathematics', url: 'pages/pca.html', models: ['PCA'] },
  { term: 'Eigenvector', kind: 'mathematics', url: 'pages/pca.html', models: ['PCA'] },
  { term: 'Covariance Matrix', kind: 'mathematics', url: 'pages/pca.html', models: ['PCA', 'Multiple Linear Regression'] },
  { term: 'Covariance', kind: 'statistics', url: 'pages/mathematics.html#covariance', models: ['PCA'] },
  { term: 'Correlation', kind: 'statistics', url: 'pages/mathematics.html#correlation', models: ['Linear Regression', 'PCA'] },
  { term: 'Mean Squared Error', kind: 'concept', url: 'pages/linear-regression.html', models: ['Linear Regression', 'Multiple Linear Regression', 'Polynomial', 'Ridge', 'Lasso'] },
  { term: 'Log-loss / Cross-entropy', kind: 'concept', url: 'pages/logistic-regression.html', models: ['Logistic Regression'] },
  { term: 'Maximum Likelihood', kind: 'mathematics', url: 'pages/logistic-regression.html', models: ['Logistic Regression'] },
  { term: 'Margin', kind: 'concept', url: 'pages/svm.html', models: ['SVM'] },
  { term: 'Support Vector', kind: 'concept', url: 'pages/svm.html', models: ['SVM'] },
  { term: 'Kernel Trick', kind: 'concept', url: 'pages/svm.html', models: ['SVM'] },
  { term: 'Regularization', kind: 'concept', url: 'pages/mathematics.html#regularization', models: ['Ridge Regression', 'Lasso Regression'] },
  { term: 'L1 Regularization', kind: 'concept', url: 'pages/lasso-regression.html', models: ['Lasso Regression'] },
  { term: 'L2 Regularization', kind: 'concept', url: 'pages/ridge-regression.html', models: ['Ridge Regression'] },
  { term: 'Bias-Variance Tradeoff', kind: 'concept', url: 'pages/mathematics.html#bias-variance', models: ['Ridge', 'Lasso', 'Polynomial', 'KNN'] },
  { term: 'Softmax', kind: 'mathematics', url: 'pages/logistic-regression.html', models: ['Logistic Regression (multinomial)'] },
  { term: 'Sigmoid', kind: 'mathematics', url: 'pages/logistic-regression.html', models: ['Logistic Regression'] },
  { term: 'Distance Metric', kind: 'concept', url: 'pages/knn.html', models: ['KNN', 'K-Means', 'DBSCAN', 'Hierarchical'] },
  { term: 'Euclidean Distance', kind: 'concept', url: 'pages/knn.html', models: ['KNN', 'K-Means', 'Hierarchical'] },
  { term: 'Curse of Dimensionality', kind: 'concept', url: 'pages/knn.html', models: ['KNN', 'PCA'] },
  { term: 'Lloyd Algorithm', kind: 'concept', url: 'pages/kmeans.html', models: ['K-Means'] },
  { term: 'Inertia / WCSS', kind: 'concept', url: 'pages/kmeans.html', models: ['K-Means'] },
  { term: 'Elbow Method', kind: 'concept', url: 'pages/kmeans.html', models: ['K-Means'] },
  { term: 'Dendrogram', kind: 'concept', url: 'pages/hierarchical-clustering.html', models: ['Hierarchical Clustering'] },
  { term: 'Linkage', kind: 'concept', url: 'pages/hierarchical-clustering.html', models: ['Hierarchical Clustering'] },
  { term: 'Density', kind: 'concept', url: 'pages/dbscan.html', models: ['DBSCAN'] },
  { term: 'Neighbourhood', kind: 'concept', url: 'pages/dbscan.html', models: ['DBSCAN'] },
  { term: 'Bagging', kind: 'concept', url: 'pages/random-forest.html', models: ['Random Forest'] },
  { term: 'Bootstrap Sampling', kind: 'concept', url: 'pages/random-forest.html', models: ['Random Forest'] },
  { term: 'Ensemble', kind: 'concept', url: 'pages/random-forest.html', models: ['Random Forest'] },
  { term: 'Feature Selection', kind: 'concept', url: 'pages/lasso-regression.html', models: ['Lasso'] },
  { term: 'Multicollinearity', kind: 'concept', url: 'pages/ridge-regression.html', models: ['Ridge', 'Multiple Linear Regression'] },
  { term: 'Normal Equations', kind: 'mathematics', url: 'pages/multiple-linear-regression.html', models: ['Linear Regression', 'Multiple Linear Regression'] },
  { term: 'Dot Product', kind: 'mathematics', url: 'pages/mathematics.html#dot-product', models: ['SVM', 'Kernel Methods'] },
  { term: 'Vector', kind: 'mathematics', url: 'pages/mathematics.html#vectors', models: ['SVM', 'PCA', 'KNN'] },
  { term: 'Matrix Multiplication', kind: 'mathematics', url: 'pages/mathematics.html#matrix-multiplication', models: ['Multiple Linear Regression', 'PCA'] },
  { term: 'Norm', kind: 'mathematics', url: 'pages/mathematics.html#norms', models: ['Ridge', 'Lasso', 'SVM', 'K-Means'] },
  { term: 'Explained Variance', kind: 'concept', url: 'pages/pca.html', models: ['PCA'] },
  { term: 'Clustering', kind: 'concept', url: 'pages/kmeans.html', models: ['K-Means', 'Hierarchical', 'DBSCAN'] },
  { term: 'Classification', kind: 'concept', url: 'pages/logistic-regression.html', models: ['Logistic Regression', 'KNN', 'Naive Bayes', 'Decision Tree', 'Random Forest', 'SVM'] },
  { term: 'Regression', kind: 'concept', url: 'pages/linear-regression.html', models: ['Linear Regression', 'Multiple Linear Regression', 'Polynomial', 'Ridge', 'Lasso'] },
  { term: 'Supervised Learning', kind: 'concept', url: 'pages/mathematics.html#supervised', models: ['All classification and regression models'] },
  { term: 'Unsupervised Learning', kind: 'concept', url: 'pages/mathematics.html#unsupervised', models: ['K-Means', 'Hierarchical', 'DBSCAN', 'PCA'] },
  { term: 'Overfitting', kind: 'concept', url: 'pages/polynomial-regression.html', models: ['Polynomial', 'Ridge', 'Lasso', 'Decision Tree'] },
  { term: 'Anomaly Detection', kind: 'application', url: 'pages/dbscan.html', models: ['DBSCAN', 'K-Means'] }
];

export default CONCEPTS;